# Generated by Django 3.2.10 on 2021-12-18 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edapp', '0003_auto_20211215_1541'),
    ]

    operations = [
        migrations.CreateModel(
            name='blogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1024)),
                ('description', models.TextField()),
                ('written_by', models.CharField(max_length=1024)),
                ('created_at', models.DateField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Blogs',
            },
        ),
        migrations.AddField(
            model_name='course',
            name='aim',
            field=models.CharField(default='To Provude better knowledge', max_length=1024),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='methodology',
            field=models.CharField(default='Live Interaction', max_length=1024),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='objective',
            field=models.CharField(default='Stress free', max_length=1024),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='topics',
            field=models.CharField(default='Mental Health', max_length=1024),
            preserve_default=False,
        ),
    ]
