# Generated by Django 3.2.10 on 2021-12-28 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('edapp', '0004_auto_20211218_1752'),
    ]

    operations = [
        migrations.CreateModel(
            name='social_media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1054)),
                ('pic', models.ImageField(upload_to='icons/')),
            ],
        ),
        migrations.CreateModel(
            name='team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pic', models.ImageField(upload_to='teams/')),
                ('name', models.CharField(max_length=1024)),
                ('title', models.CharField(max_length=1024)),
                ('description', models.CharField(max_length=1024)),
                ('fb', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Facebook', to='edapp.social_media')),
                ('linkdin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Linkdin', to='edapp.social_media')),
                ('twitter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Twitter', to='edapp.social_media', verbose_name='Twitter')),
            ],
        ),
    ]
