# Generated by Django 3.2.10 on 2021-12-28 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('edapp', '0005_social_media_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='fb',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Facebook', to='edapp.social_media', verbose_name='Facebook'),
        ),
        migrations.AlterField(
            model_name='team',
            name='linkdin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Linkdin', to='edapp.social_media', verbose_name='Linkdin'),
        ),
    ]
